site_name: 'DevSecOps-pipeline'
nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statements: 'Problem-statements'
- Setting up VM: 'setting-up-VM.md'
- Setting up Jenkins: 'setting-up-jenkins.md'
- Setting up mkDocs: 'setting-up-mkdocs.md'
- Setting up pipeline: 'setting-up-pipeline.md'
- Setting up DVNA: 'setting-up-dvna.md'
- Static Analysis: 'SAST.md'
- Software Composition Analysis: 'software-composition-analysis.md'
- Dynamic Analysis: 'DAST.md'
- Source Code Quality Analysis: 'Source-Code-Quality-Analysis.md'
- Complete Pipeline  Structure: 'Complete-pipeline.md'
- Resources: 'Resources.md'
theme: material