site_name: 'DevSecOps-pipeline'
nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Setting up VM: 'setting-up-VM.md'
- Setting up Jenkins: 'setting-up-jenkins.md'
- Setting up mkDocs: 'setting-up-mkdocs.md'
- Setting up pipeline: 'setting-up-pipeline.md'
- Setting up DVNA: 'setting-up-dvna.md'
- Source-Code-Quality-Analysis: 'Source-Code-Quality-Analysis.md'
- SCA : 'SCA.md'
- SAST: 'SAST.md'
- Working-of-pipeline: 'Working-of-pipeline.md'
theme: material